### PR TITLE
Original satoshi nakamoto e-mail

### PR DESCRIPTION
**Pull request by Jetro-Costa**
https://www.metzdowd.com/pipermail/cryptography/2008-November/014814.html

### CODE REVIEW

**Comment by Jetro-Costa** [comment]
Sorry, I do not reade the documentation

**Comment by 0xB10C** [comment]
Thanks for this contribution! I agree that it's better to link to the original archive of the mail. Looking into it I saw that both the old and new link both point to a reply from James A. Donald and not the original mail Satoshi sent. I think we should link to this mail: https://www.metzdowd.com/pipermail/cryptography/2008-October/014810.html


What do you think? Do you want to update your commit?

**Comment by Jetro-Costa** [comment]
It is speculated that he was developing bitcoin long before without help, but this is in private emails that were leaked.
You better update the commit, I don't use all documentation. Excuse!

**Comment by 0xB10C** [comment]
Picked up your suggestion in https://github.com/0xB10C/bitcoin-development-history/pull/14 and added you as co-author! Thank you.

**Pull request closed without merging**
